version: "3.9"

services:
  web-server:
    build: .
    expose:
      - ${SERVER_PORT}
    env_file:
      - .env

  caddy:
    image: caddy:latest
    env_file:
      - .env
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - "8080:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web-server

volumes:
  caddy_data:
  caddy_config:
